make --detect-commit the default behaviour
cqse/teamscale-upload pull request #23
Opened 2020-11-30 16:04 UTC by karottenreibe

Addresses issue TS-XXXXX

- [x] Changes are tested adequately
- [] Teamscale documentation updated in case of relevant user-visible changes
- [x] CHANGELOG.md updated
- [x] Present new features in [N&N](https://wiki.cqse.eu/pages/viewpage.action?pageId=689566) not needed

Please respect the vote of the [Teamscale bot](https://demo.teamscale.com) or flag irrelevant findings as tolerated or false positives. If you feel that the Teamscale config or architecture file needs adjustment, please state so in a comment and discuss this with your reviewer.

2020-11-30 19:16 UTC, karottenreibe commented
need to update TS docs after merging and releasing

2020-12-02 08:49 UTC, saileru requested changes
Nice 🙂 Only one minor comment.

2020-12-02 08:49 UTC, saileru commented on src/main/java/com/cqse/teamscaleupload/TeamscaleUpload.java
> +                throw new ArgumentParserException("You used more than one of --detect-commit, --commit and --branch-and-timestamp." +
As we removed the `detect-commit` option, we should not mention it here anymore, right?

2020-12-02 08:55 UTC, karottenreibe commented
thanks @saileru fixed that :-)

2020-12-02 09:23 UTC, merged