TS-28611 Implemented passing access key securely via stdin or environ…
cqse/teamscale-upload pull request #36
Opened 2022-01-04 15:35 UTC by yoshc

…ment variable; Reformatted code

Addresses issue TS-28611

- [ ] Changes are tested adequately
- [ ] Teamscale documentation updated in case of relevant user-visible changes
- [ ] CHANGELOG.md updated
- [ ] Present new features in [N&N](https://wiki.cqse.eu/pages/viewpage.action?pageId=689566)

Please respect the vote of the [Teamscale bot](https://demo.teamscale.com) or flag irrelevant findings as tolerated or
false positives. If you feel that the Teamscale config or architecture file needs adjustment, please state so in a
comment and discuss this with your reviewer.

2022-01-05 15:26 UTC, saileru requested changes
@yoshc Thanks for implementing this. I thought it would be valuable to have a automatic tests for the new functionality, so I spent some time and added a few tests in a new commit. In the process I also did some minor rework. It would be great if you could review my changes 🙂

2022-01-05 15:26 UTC, saileru commented on .github/workflows/actions.yml
> +          TEAMSCALE_ACCESS_KEY: ${{ secrets.TEAMSCALE_ACCESS_KEY }}
As we now support passing the access key via environment variable directly, we can also use this for the tests. Previously, we only read the access key from the environment variable to put it into the command line option for the tests. I adjusted the tests accordingly and also made the naming of the enviromnent variables consistent here for the access key which is read from the Github secret.

2022-01-05 15:26 UTC, saileru commented on src/main/java/com/teamscale/upload/CommandLine.java
>  	}
I did this already in my rework. Please have a look if this makes sense 🙂

2022-01-05 15:52 UTC, saileru commented on src/main/java/com/teamscale/upload/CommandLine.java
> +	 * $TEAMSCALE_ACCESSKEY.
Did that already 🙂

2022-01-05 16:01 UTC, saileru commented on src/test/java/com/teamscale/upload/NativeImageIT.java
> +			}
I would tend to tolerate the long-method finding here. I do not see a way to improve this by extracting methods...

2022-01-10 08:45 UTC, yoshc commented on src/main/java/com/teamscale/upload/CommandLine.java
> +							+ TEAMSCALE_ACCESS_KEY_ENVIRONMENT_VARIABLE + " or via stdin" + " using '--accesskey -'.",
I think the last string concatenation got mixed up by the change and can be removed. Will do this in my rework

2022-01-10 10:31 UTC, j-christl commented on src/test/java/com/teamscale/upload/NativeImageIT.java
> +		private String stdin = null;
Refactored

2022-01-10 10:31 UTC, j-christl commented on src/test/java/com/teamscale/upload/NativeImageIT.java
> +			// number of spaces this behaviour can unfortunately not be disabled
Added dot

2022-01-10 15:28 UTC, saileru commented on src/main/java/com/teamscale/upload/autodetect_revision/ProcessUtils.java
> +		CaptureStreamHandler handler = new CaptureStreamHandler(input);
I had a look at the source code: https://commons.apache.org/proper/commons-exec/apidocs/src-html/org/apache/commons/exec/PumpStreamHandler.html#line.76
```
075    /**
076     * Construct a new <CODE>PumpStreamHandler</CODE>.
077     *
078     * @param out the output <CODE>OutputStream</CODE>.
079     * @param err the error <CODE>OutputStream</CODE>.
080     */
081    public PumpStreamHandler(final OutputStream out, final OutputStream err) {
082        this(out, err, null);
083    }
```
There, they also pass null as `input` in the two-argument constructor. So, I assume that `null` is a valid value here and simply means "no input stream".

2022-01-10 15:34 UTC, saileru approved these changes
Nice, thanks 🙂

2022-01-10 15:35 UTC, merged